### ISSUE TITLE
Parameter error in Check_MK Raw Edition 1.2.8p20

### ISSUE THREAD

**Issue by mbirth** [mape2k/check_mk_extensions#1]
The service scan shows:

> Invalid check parameter: Undefined key 'length' in the dictionary. Allowed are deferred, active.! The parameter is: {'deferred': (10, 30), 'length': (10, 20), 'age': (3600, 7200), 'size': (1048576, 2097152)} The variable name is: checkgroup_parameters:mailqueue_length

In that version of Check_MK, you can actually define `mailqueue_length` parameters in the rules - but only `deferred` and `active` limits, no age or length.

**Comment by mape2k** [comment]
Thank you for your issue and sorry for the long delay.
As this error is reported for an very old version, we'll not fix this.

A new version for checkmk 2 will be released soon.
