### ISSUE TITLE
WARNING: Parsing of section nut failed - please submit a crash report!

### ISSUE THREAD

**Issue by 47k** [mape2k/check_mk_extensions#11]
Thank you for your CheckMK nut Plugin. I installed the agent file (nut) on the host and I got information about the ups. 
But when I try to get the service into checkmk, I got this issue during the discovery:

WARNING: Parsing of section nut failed - please submit a crash report! (Crash-ID: 7f36e572-a61b-11ed-ab44-00155d4d190e)

**Comment by mape2k** [comment]
Please add output of nut agent plugin and output of cmk if possible.
Therefore ran "cmk --debug -nv --checks=nut HOSTNAME" as the corresponding omd user.

**Comment by 47k** [comment]
**./nut Plugin Output:**

```
<<<nut>>>
==> usv <==
battery.charge: 100.00
battery.date: 06/15/2022
battery.mfr.date: 2022/05/26
battery.runtime: 6000.00
battery.runtime.low: 120
battery.voltage: 54.60
device.mfr: APC
device.model: Smart-UPS 1500
device.serial: AS567551389
device.type: ups
driver.name: snmp-ups
driver.parameter.pollinterval: 2
driver.parameter.port: 10.1.0.111
driver.parameter.synchronous: no
driver.version: 2.7.4
driver.version.data: apcc MIB 1.2
driver.version.internal: 0.97
input.frequency: 50.00
input.sensitivity: medium
input.transfer.high: 257
input.transfer.low: 203
input.transfer.reason: noTransfer
input.voltage: 228.90
input.voltage.maximum: 228.80
input.voltage.minimum: 227.50
output.current: 1.00
output.frequency: 50.00
output.voltage: 228.90
output.voltage.nominal: 230
ups.firmware: UPS 09.2 (ID18)
ups.id: USV8
ups.load: 10.40
ups.mfr: APC
ups.mfr.date: 06/19/2015
ups.model: Smart-UPS 1500
ups.serial: AS56755431389
ups.status: OL
ups.temperature: 19.30
ups.test.date: 07/20/2022
ups.test.result: Normal
```
There is no output regarding nut or no special output. Only this one if I do an "cmk -I":

`WARNING: Parsing of section nut failed - please submit a crash report! (Crash-ID: 6bc9410e-a66d-11ed-bf75-00155d4d190e)`

**Comment by mape2k** [comment]
Your output contains float instead of integer for runtime and load and misses beeper status.
Could you please test nut-2.0.2.mkp from https://github.com/mape2k/check_mk_extensions/tree/cmk2.0_fix_float_values/nut. This should hopefully fix this issue.

**Comment by 47k** [comment]
Thank you for your fast reply - unfortunately the same issue: WARNING: Parsing of section nut failed - please submit a crash report! (Crash-ID: 9b4a39ce-a6bd-11ed-bc81-00155d4d190e)

The agent output is still the same, but yeah, the agent plugin is not changed.

**Comment by mape2k** [comment]
> The agent output is still the same, but yeah, the agent plugin is not changed.

Did you install nut-2.0.2.mkp? There are changes in the discovery modules. Agent plugin was unchanged.

**Comment by 47k** [comment]
My fault - 2.0.2 it's not replacing the old version, so I had to activate it. It seems to be working - thank you! :)

**Comment by mape2k** [comment]
> My fault - 2.0.2 it's not replacing the old version, so I had to activate it. It seems to be working - thank you! :)

Thank you for testing. I'll release 2.0.2 also via checkmk exchange
