### ISSUE TITLE
nut - cmk

### ISSUE THREAD

**Issue by nevusZ** [mape2k/check_mk_extensions#7]
Hallo,
ich hab cmk 2.1.0p19 auf einer ubuntu vm installiert und kann den nut server (synology nas) per upsc abfragen

upsc ups@192.168.11.9
Init SSL without certificate database
battery.charge: 100
battery.charge.low: 10
battery.charge.warning: 50
battery.runtime: 4860
battery.runtime.low: 120
battery.type: PbAc
battery.voltage: 26.8
battery.voltage.nominal: 24.0
device.mfr: American Power Conversion
device.model: Smart-UPS 750
device.serial: 1234567890
device.type: ups
driver.name: usbhid-ups
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 5
driver.parameter.port: auto
driver.parameter.synchronous: no
driver.version: DSM7-1-1-42930-workplus-version2-repack-42930-220712
driver.version.data: APC HID 0.96
driver.version.internal: 0.41
ups.beeper.status: enabled
ups.delay.shutdown: 20
ups.firmware: UPS 09.3 / ID=18
ups.mfr: American Power Conversion
ups.mfr.date: 2016/06/09
ups.model: Smart-UPS 750
ups.productid: 0003
ups.serial: 1234567890
ups.status: OL
ups.timer.reboot: -1
ups.timer.shutdown: -1
ups.vendorid: 051d

habe nut mkp installiert 
OMD[prod]:~$ mkp list
nut
OMD[prod]:~$

wenn ich die synology nas neue services discovery taucht nichts auf?

was muss bei parameters unter UPS eingegeben werden?

bitte danke

**Comment by mape2k** [comment]
Du musst das Agent-Plugin "nut" unter agents/plugins in den Plugin-Ordner vom Agenten auf die Synology kopieren und mit chmod +x nut ausführbar machen. Dann fragt der Agent die UPS lokal ab und überträgt die Daten an den Server. Solltes du deine Synology per SNMP abfragen, dann kann dir die Erweiterung nicht weiterhelfen, da sie Agenten-basiert funktioniert.

**Comment by nevusZ** [comment]
servus,
[https://imgur.com/a/eOPUfQ2](url)
ich hab version 2.1.0p27, das paket lässt sich am cmk server nicht aktivieren.

am agent kommt folgender fehler "check_mk_agent -d 2>&1 | less"

+ _log_section_time python3 ./nut.py
+ python3 ./nut.py
Traceback (most recent call last):
  File "/usr/lib/check_mk_agent/plugins/./nut.py", line 27, in <module>
    from .agent_based_api.v1 import (
ImportError: attempted relative import with no known parent package
+ for script in [1-9]*/*
+ is_valid_plugin '[1-9]*/*'
+ case "${1:?No plugin defined}" in
+ '[' -f '[1-9]*/*' ']'
+ true
+ main_async_parts
+ run_real_time_checks
+ RTC_PLUGINS=
+ . /etc/check_mk/real_time_checks.cfg
+ return
+ true
+ main_finalize_sync
+ finalize_profiling
+ :
+ '[' '' -gt 0 ']'
+ return 0

funktioniert das plugin nicht mit 2.1.0?
die ups hängt jetzt bei mir bei einem proxmox server

**Comment by nevusZ** [comment]
das problem war das ich das plugin in das agent verzeichnis kopiert habe.
nachdem ich das richtige file kopiert habe liefert der agent die NUT werte
<<<nut>>>
==> ups <==
battery.charge: 100
battery.charge.low: 10
battery.charge.warning: 50
battery.runtime: 2640
battery.runtime.low: 600
battery.type: PbAc
battery.voltage: 26.8
battery.voltage.nominal: 24.0
device.mfr: American Power Conversion
device.model: Smart-UPS 750
device.serial: 3S1623X04675
device.type: ups
driver.flag.pollonly: enabled
driver.name: usbhid-ups
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 15
driver.parameter.port: auto
driver.parameter.productid: 0003
driver.parameter.serial: 1234567890
driver.parameter.synchronous: no
driver.parameter.vendorid: 051D
driver.version: 2.7.4
driver.version.data: APC HID 0.96
driver.version.internal: 0.41
ups.beeper.status: enabled
ups.delay.shutdown: 20
ups.firmware: UPS 09.3 / ID=18
ups.mfr: American Power Conversion
ups.mfr.date: 2016/06/09
ups.model: Smart-UPS 750
ups.productid: 0003
ups.serial: 1234567890
ups.status: OL
ups.timer.reboot: -1
ups.timer.shutdown: -1
ups.vendorid: 051d

beim cmk sehe ich die werte aber noch nicht, auch nicht nach neuem service discovery

**Comment by nevusZ** [comment]
habe eine rule angelegt unter WATO->Network UPS Tools->
dann kommt beim activate dieser fehler
<html>
<body>


  | Started at: 11:41:17. Finished at: 11:41:20.Warnings:check_mk: Found configured rules of deprecated check group "nut". These rules are not used by any check plugin. Maybe this check group has been renamed during an update, in this case you will have to migrate your configuration to the new ruleset manually. Please check out the release notes of the involved versions. You may use the page "Deprecated rules" in the "Rule search" to view your rules and move them to the new rulesets. If this is not the case, the rules could be related to a disabled or removed extension package (mkp). You would have to enable/upload the corresponding package and remove the related rules before disabling/removing the package again.
-- | --



</body>
</html>

**Comment by nevusZ** [comment]
OMD[prod]:~$ mkp list
Name Version Title             Author                                     Req. Version Until Version Files State
---- ------- ----------------- ------------------------------------------ ------------ ------------- ----- -------------------------------
nut  2.0.2   Network UPS Tools Marcel Pennewiss <opensource@pennewiss.de> 2.0.0        None          6     Enabled (inactive on this site)
OMD[prod]:~$

es hat wohl mit version 2.1.0 zu tun

**Comment by nevusZ** [comment]
mkp disable 
mkp remove 
mkp find
mkp list
manuell alles löschen
neustart omd
mkp install

OMD[prod]:~$ mkp list
Name Version Title             Author                                     Req. Version Until Version Files State
---- ------- ----------------- ------------------------------------------ ------------ ------------- ----- -----------------------------
nut  2.0.2   Network UPS Tools Marcel Pennewiss <opensource@pennewiss.de> 2.0.0        None          6     Enabled (active on this site)
OMD[prod]:~$

dann hat es funktioniert
USV ist jetzt im CMK
