### ISSUE TITLE
Multile UPS on single instance of NuT

### ISSUE THREAD

**Issue by notenoughcash** [mape2k/check_mk_extensions#8]
Using on Pi w/NUT to monitor two UPS devices in the same home lab area, in Checkmk both are identified correctly by name as two services, however they are both using the same service performance data from ==> Tripplite-Rack <== in the GUI effectively meaning one UPS is not monitored.

---editied to relevant info per UPS---

pi@pihole:/usr/lib/check_mk_agent/plugins $ ./nut
<<<nut>>>
==> Tripplite-Network <==
battery.charge: 100
battery.runtime: 5760
battery.type: PbAC
battery.voltage: 13.5
battery.voltage.nominal: 12.0
device.mfr: Tripp Lite
device.model: Tripp Lite UPS
device.type: ups
input.frequency: 60.0
input.voltage: 120.3
input.voltage.nominal: 120
output.frequency.nominal: 60
output.voltage.nominal: 120
ups.beeper.status: enabled

==> Tripplite-Rack <==
battery.charge: 100
battery.runtime: 4050
battery.type: PbAc
battery.voltage: 26.9
battery.voltage.nominal: 24.0
device.mfr: Tripp Lite
device.model: TRIPP LITE UPS
input.frequency: 59.8
input.voltage: 120.1
input.voltage.nominal: 120
output.frequency.nominal: 60
output.voltage.nominal: 120
ups.beeper.status: enabled

**Comment by mape2k** [comment]
Thank you for your bug report. This issue was already reported by mail.
I'll try to fix this in the next days.

**Comment by notenoughcash** [comment]
Thank you

**Comment by mape2k** [comment]
Released nut 2.0.1 in repo and exchange.checkmk.com which should fix your issue and some others.
Could you please test and give some feedback?

**Comment by notenoughcash** [comment]
That looks like it fixed it, will be adding a third UPS in a few days for further testing.

Thank you!

**Comment by mape2k** [comment]
> That looks like it fixed it, will be adding a third UPS in a few days for further testing.

Thanks for testing. Please open a new issue on further problems.
